from .. import BaseProvider


class Provider(BaseProvider):
    sentences = [
        "Now , fair Hippolyta , our nuptial hour",
        "Draws on apace : four happy days bring in",
        "Another moon ; but O ! methinks how slow",
        "This old moon wanes ; she lingers my desires",
        "Like to a step dame , or a dowager",
        "Long withering out a young man's revenue",
        "Four days will quickly steep themselves in night",
        "Four nights will quickly dream away the time",
        "And then the moon , like to a silver bow",
        "New-bent in heaven , shall behold the night",
        "Of our solemnities",
        "Go , Philostrate",
        "Stir up the Athenian youth to merriments",
        "Awake the pert and nimble spirit of mirth",
        "Turn melancholy forth to funerals",
        "The pale companion is not for our pomp",
        "Hippolyta , I woo'd thee with my sword",
        "And won thy love doing thee injuries",
        "But I will wed thee in another key",
        "With pomp , with triumph , and with revelling",
        "Happy be Theseus , our renowned duke !",
        "Thanks , good Egeus : what's the news with thee ?",
        "Full of vexation come I , with complaint",
        "Against my child , my daughter Hermia",
        "Stand forth , Demetrius . My noble lord",
        "This man hath my consent to marry her",
        "Stand forth , Lysander : and , my gracious duke",
        "This man hath bewitch'd the bosom of my child :",
        "Thou , thou , Lysander , thou hast given her rimes",
        "And interchang'd love-tokens with my child",
        "Thou hast by moonlight at her window sung",
        "With feigning voice , verses of feigning love",
        "And stol'n the impression of her fantasy",
        "With bracelets of thy hair , rings , gawds , conceits",
        "Knacks , trifles , nosegays , sweetmeats , messengers",
        "Of strong prevailment in unharden'd youth",
        "With cunning hast thou filch'd my daughter's heart",
        "Turn'd her obedience , which is due to me",
        "To stubborn harshness . And , my gracious duke",
        "Be it so she will not here before your Grace",
        "Consent to marry with Demetrius",
        "I beg the ancient privilege of Athens",
        "As she is mine , I may dispose of her",
        "Which shall be either to this gentleman",
        "Or to her death , according to our law",
        "Immediately provided in that case",
        "What say you , Hermia ? be advis'd , fair maid",
        "To you , your father should be as a god",
        "One that compos'd your beauties , yea , and one",
        "To whom you are but as a form in wax",
        "By him imprinted , and within his power",
        "To leave the figure or disfigure it",
        "Demetrius is a worthy gentleman",
        "So is Lysander",
        "In himself he is",
        "But , in this kind , wanting your father's voice",
        "The other must be held the worthier",
        "I would my father look'd but with my eyes",
        "Rather your eyes must with his judgment look",
        "I do entreat your Grace to pardon me",
        "I know not by what power I am made bold",
        "Nor how it may concern my modesty",
        "In such a presence here to plead my thoughts",
        "But I beseech your Grace , that I may know",
        "The worst that may befall me in this case",
        "If I refuse to wed Demetrius",
        "Either to die the death , or to abjure",
        "For ever the society of men",
        "Therefore , fair Hermia , question your desires",
        "Know of your youth , examine well your blood",
        "Whe'r , if you yield not to your father's choice",
        "You can endure the livery of a nun",
        "For aye to be in shady cloister mew'd",
        "To live a barren sister all your life",
        "Chanting faint hymns to the cold fruitless moon",
        "Thrice blessed they that master so their blood",
        "To undergo such maiden pilgrimage",
        "But earthlier happy is the rose distill'd",
        "Than that which withering on the virgin thorn",
        "Grows , lives , and dies , in single blessedness",
        "So will I grow , so live , so die , my lord",
        "Ere I will yield my virgin patent up",
        "Unto his lordship , whose unwished yoke",
        "My soul consents not to give sovereignty",
        "Take time to pause ; and , by the next new moon",
        "The sealing-day betwixt my love and me",
        "For everlasting bond of fellowship",
        "Upon that day either prepare to die",
        "For disobedience to your father's will",
        "Or else to wed Demetrius , as he would",
        "Or on Diana's altar to protest",
        "For aye austerity and single life",
        "Relent , sweet Hermia ; and , Lysander , yield",
        "Thy crazed title to my certain right",
        "You have her father's love , Demetrius",
        "Let me have Hermia's : do you marry him",
        "Scornful Lysander ! true , he hath my love",
        "And what is mine my love shall render him",
        "And she is mine , and all my right of her",
        "I do estate unto Demetrius",
        "I am , my lord , as well deriv'd as he",
        "As well possess'd ; my love is more than his",
        "My fortunes every way as fairly rank'd",
        "If not with vantage , as Demetrius'",
        "And , which is more than all these boasts can be",
        "I am belov'd of beauteous Hermia",
        "Why should not I then prosecute my right ?",
        "Demetrius , I'll avouch it to his head",
        "Made love to Nedar's daughter , Helena",
        "And won her soul ; and she , sweet lady , dotes",
        "Devoutly dotes , dotes in idolatry",
        "Upon this spotted and inconstant man",
        "I must confess that I have heard so much",
        "And with Demetrius thought to have spoke thereof",
        "But , being over-full of self-affairs",
        "My mind did lose it . But , Demetrius , come",
        "And come , Egeus ; you shall go with me",
        "I have some private schooling for you both",
        "For you , fair Hermia , look you arm yourself",
        "To fit your fancies to your father's will",
        "Or else the law of Athens yields you up",
        "Which by no means we may extenuate",
        "To death , or to a vow of single life",
        "Come , my Hippolyta : what cheer , my love ?",
        "Demetrius and Egeus , go along :",
        "I must employ you in some business",
        "Against our nuptial , and confer with you",
        "Of something nearly that concerns yourselves",
        "With duty and desire we follow you",
        "How now , my love ! Why is your cheek so pale ?",
        "How chance the roses there do fade so fast ?",
        "Belike for want of rain , which I could well",
        "Beteem them from the tempest of mine eyes",
        "Ay me ! for aught that ever I could read",
        "Could ever hear by tale or history",
        "The course of true love never did run smooth",
        "But , either it was different in blood",
        "O cross ! too high to be enthrall'd to low",
        "Or else misgraffed in respect of years",
        "O spite ! too old to be engag'd to young",
        "Or else it stood upon the choice of friends",
        "O hell ! to choose love by another's eye",
        "Or , if there were a sympathy in choice",
        "War , death , or sickness did lay siege to it",
        "Making it momentany as a sound",
        "Swift as a shadow , short as any dream",
        "Brief as the lightning in the collied night",
        "That , in a spleen , unfolds both heaven and earth",
        "And ere a man hath power to say , 'Behold !'",
        "The jaws of darkness do devour it up :",
        "So quick bright things come to confusion",
        "If then true lovers have been ever cross'd",
        "It stands as an edict in destiny :",
        "Then let us teach our trial patience",
        "Because it is a customary cross",
        "As due to love as thoughts and dreams and sighs",
        "Wishes and tears , poor fancy's followers",
        "A good persuasion : therefore , hear me , Hermia",
        "I have a widow aunt , a dowager",
        "Of great revenue , and she hath no child :",
        "From Athens is her house remote seven leagues",
        "And she respects me as her only son",
        "There , gentle Hermia , may I marry thee",
        "And to that place the sharp Athenian law",
        "Cannot pursue us . If thou lov'st me then",
        "Steal forth thy father's house to-morrow night",
        "And in the wood , a league without the town",
        "Where I did meet thee once with Helena",
        "To do observance to a morn of May",
        "There will I stay for thee",
        "My good Lysander !",
        "I swear to thee by Cupid's strongest bow",
        "By his best arrow with the golden head",
        "By the simplicity of Venus' doves",
        "By that which knitteth souls and prospers loves",
        "And by that fire which burn'd the Carthage queen",
        "When the false Troyan under sail was seen",
        "By all the vows that ever men have broke",
        "In number more than ever women spoke",
        "In that same place thou hast appointed me",
        "To-morrow truly will I meet with thee",
        "Keep promise , love . Look , here comes Helena",
        "God speed fair Helena ! Whither away ?",
        "Call you me fair ? that fair again unsay",
        "Demetrius loves your fair : O happy fair !",
        "Your eyes are lode-stars ! and your tongue's sweet air",
        "More tuneable than lark to shepherd's ear",
        "When wheat is green , when hawthorn buds appear",
        "Sickness is catching : O ! were favour so",
        "Yours would I catch , fair Hermia , ere I go",
        "My ear should catch your voice , my eye your eye",
        "My tongue should catch your tongue's sweet melody",
        "Were the world mine , Demetrius being bated",
        "The rest I'd give to be to you translated",
        "O ! teach me how you look , and with what art",
        "You sway the motion of Demetrius' heart",
        "I frown upon him , yet he loves me still",
        "O ! that your frowns would teach my smiles such skill",
        "I give him curses , yet he gives me love",
        "O ! that my prayers could such affection move",
        "The more I hate , the more he follows me",
        "The more I love , the more he hateth me",
        "His folly , Helena , is no fault of mine",
        "None , but your beauty : would that fault were mine !",
        "Take comfort : he no more shall see my face",
        "Lysander and myself will fly this place",
        "Before the time I did Lysander see",
        "Seem'd Athens as a paradise to me :",
        "O ! then , what graces in my love do dwell",
        "That he hath turn'd a heaven unto a hell",
        "Helen , to you our minds we will unfold",
        "To-morrow night , when Ph be doth behold",
        "Her silver visage in the wat'ry glass",
        "Decking with liquid pearl the bladed grass",
        "A time that lovers' flights doth still conceal",
        "Through Athens' gates have we devis'd to steal",
        "And in the wood , where often you and I",
        "Upon faint primrose-beds were wont to lie",
        "Emptying our bosoms of their counsel sweet",
        "There my Lysander and myself shall meet",
        "And thence from Athens turn away our eyes",
        "To seek new friends and stranger companies",
        "Farewell , sweet playfellow : pray thou for us",
        "And good luck grant thee thy Demetrius !",
        "Keep word , Lysander : we must starve our sight",
        "From lovers' food till morrow deep midnight",
        "I will , my Hermia",
        "Helena , adieu :",
        "As you on him , Demetrius dote on you !",
        "How happy some o'er other some can be !",
        "Through Athens I am thought as fair as she",
        "But what of that ? Demetrius thinks not so",
        "He will not know what all but he do know",
        "And as he errs , doting on Hermia's eyes",
        "So I , admiring of his qualities",
        "Things base and vile , holding no quantity",
        "Love can transpose to form and dignity",
        "Love looks not with the eyes , but with the mind",
        "And therefore is wing'd Cupid painted blind",
        "Nor hath Love's mind of any judgment taste",
        "Wings and no eyes figure unheedy haste :",
        "And therefore is Love said to be a child",
        "Because in choice he is so oft beguil'd",
        "As waggish boys in game themselves forswear",
        "So the boy Love is perjur'd every where",
        "For ere Demetrius look'd on Hermia's eyne",
        "He hail'd down oaths that he was only mine",
        "And when this hail some heat from Hermia felt",
        "So he dissolv'd , and showers of oaths did melt",
        "I will go tell him of fair Hermia's flight :",
        "Then to the wood will he to-morrow night",
        "Pursue her ; and for this intelligence",
        "If I have thanks , it is a dear expense :",
        "But herein mean I to enrich my pain",
        "To have his sight thither and back again",
        "Is all our company here ?",
        "You were best to call them generally , man by man , according to the scrip",
        "Here is the scroll of every man's name , which is thought fit , through all Athens , to play in our interlude before the duke and the duchess on his wedding-day at night",
        "First , good Peter Quince , say what the play treats on ; then read the names of the actors , and so grow to a point",
        "Marry , our play is , The most lamentable comedy , and most cruel death of Pyramus and Thisby",
        "A very good piece of work , I assure you , and a merry . Now , good Peter Quince , call forth your actors by the scroll . Masters , spread yourselves",
        "Answer as I call you . Nick Bottom , the weaver",
        "Ready . Name what part I am for , and proceed",
        "You , Nick Bottom , are set down for Pyramus",
        "What is Pyramus ? a lover , or a tyrant ?",
        "A lover , that kills himself most gallantly for love",
        "That will ask some tears in the true performing of it : if I do it , let the audience look to their eyes ; I will move storms , I will condole in some measure . To the rest : yet my chief humour is for a tyrant . I could play Ercles rarely , or a part to tear a cat in , to make all split",
        "The raging rocks",
        "And shivering shocks",
        "Shall break the locks",
        "Of prison gates :",
        "And Phibbus' car",
        "Shall shine from far",
        "And make and mar",
        "The foolish Fates",
        "This was lofty ! Now name the rest of the players . This is Ercles' vein , a tyrant's vein ; a lover is more condoling",
        "Francis Flute , the bellows-mender",
        "Here , Peter Quince",
        "You must take Thisby on you",
        "What is Thisby ? a wandering knight ?",
        "It is the lady that Pyramus must love",
        "Nay , faith , let not me play a woman ; I have a beard coming",
        "That's all one : you shall play it in a mask , and you may speak as small as you will",
        "An I may hide my face , let me play Thisby too . I'll speak in a monstrous little voice , 'Thisne , Thisne !' 'Ah , Pyramus , my lover dear ; thy Thisby dear , and lady dear !'",
        "No , no ; you must play Pyramus ; and Flute , you Thisby",
        "Well , proceed",
        "Robin Starveling , the tailor",
        "Here , Peter Quince",
        "Robin Starveling , you must play Thisby's mother . Tom Snout , the tinker",
        "Here , Peter Quince",
        "You , Pyramus's father ; myself , Thisby's father ; Snug , the joiner , you the lion's part : and , I hope , here is a play fitted",
        "Have you the lion's part written ? pray you , if it be , give it me , for I am slow of study",
        "You may do it extempore , for it is nothing but roaring",
        "Let me play the lion too . I will roar , that I will do any man's heart good to hear me ; I will roar , that I will make the duke say , 'Let him roar again , let him roar again .'",
        "An you should do it too terribly , you would fright the duchess and the ladies , that they would shriek ; and that were enough to hang us all",
        "That would hang us , every mother's son",
        "I grant you , friends , if that you should fright the ladies out of their wits , they would have no more discretion but to hang us ; but I will aggravate my voice so that I will roar you as gently as any sucking dove ; I will roar you as 'twere any nightingale",
        "You can play no part but Pyramus ; for Pyramus is a sweet-faced man ; a proper man , as one shall see in a summer's day ; a most lovely , gentleman-like man ; therefore , you must needs play Pyramus",
        "Well , I will undertake it . What beard were I best to play it in ?",
        "Why , what you will",
        "I will discharge it in either your straw-colour beard , your orange-tawny beard , your purple-in-grain beard , or your French-crown colour beard , your perfect yellow",
        "Some of your French crowns have no hair at all , and then you will play bare-faced . But masters , here are your parts ; and I am to entreat you , request you , and desire you , to con them by to-morrow night , and meet me in the palace wood , a mile without the town , by moonlight : there will we rehearse ; for if we meet in the city , we shall be dogged with company , and our devices known . In the meantime I will draw a bill of properties , such as our play wants . I pray you , fail me not",
        "We will meet ; and there we may rehearse more obscenely and courageously . Take pains ; be perfect ; adieu",
        "At the duke's oak we meet",
        "Enough ; hold , or cut bow-strings",
        "How now , spirit ! whither wander you ?",
        "Over hill , over dale",
        "Thorough bush , thorough brier",
        "Over park , over pale",
        "Thorough flood , thorough fire",
        "I do wander every where",
        "Swifter than the moone's sphere",
        "And I serve the fairy queen",
        "To dew her orbs upon the green :",
        "The cowslips tall her pensioners be",
        "In their gold coats spots you see",
        "Those be rubies , fairy favours",
        "In their freckles live their savours :",
        "I must go seek some dew-drops here",
        "And hang a pearl in every cowslip's ear",
        "Farewell , thou lob of spirits : I'll be gone",
        "Our queen and all her elves come here anon",
        "The king doth keep his revels here to-night",
        "Take heed the queen come not within his sight",
        "For Oberon is passing fell and wrath",
        "Because that she as her attendant hath",
        "A lovely boy , stol'n from an Indian king",
        "She never had so sweet a changeling",
        "And jealous Oberon would have the child",
        "Knight of his train , to trace the forests wild",
        "But she , perforce , withholds the loved boy",
        "Crowns him with flowers , and makes him all her joy",
        "And now they never meet in grove , or green",
        "By fountain clear , or spangled starlight sheen",
        "But they do square ; that all their elves , for fear",
        "Creep into acorn-cups and hide them there",
        "Either I mistake your shape and making quite",
        "Or else you are that shrewd and knavish sprite",
        "Call'd Robin Goodfellow : are you not he",
        "That frights the maidens of the villagery",
        "Skim milk , and sometimes labour in the quern",
        "And bootless make the breathless housewife churn",
        "And sometime make the drink to bear no barm",
        "Mislead night-wanderers , laughing at their harm ?",
        "Those that Hobgoblin call you and sweet Puck",
        "You do their work , and they shall have good luck :",
        "Are you not he ?",
        "Fairy , thou speak'st aright",
        "I am that merry wanderer of the night",
        "I jest to Oberon , and make him smile",
        "When I a fat and bean-fed horse beguile",
        "Neighing in likeness of a filly foal :",
        "And sometime lurk I in a gossip's bowl",
        "In very likeness of a roasted crab",
        "And , when she drinks , against her lips I bob",
        "And on her wither'd dewlap pour the ale",
        "The wisest aunt , telling the saddest tale",
        "Sometime for three-foot stool mistaketh me",
        "Then slip I from her bum , down topples she",
        "And 'tailor' cries , and falls into a cough",
        "And then the whole quire hold their hips and loff",
        "And waxen in their mirth , and neeze , and swear",
        "A merrier hour was never wasted there",
        "But , room , fairy ! here comes Oberon",
        "And here my mistress . Would that he were gone !",
        "Ill met by moonlight , proud Titania",
        "What ! jealous Oberon . Fairies , skip hence :",
        "I have forsworn his bed and company",
        "Tarry , rash wanton ! am not I thy lord ?",
        "Then , I must be thy lady ; but I know",
        "When thou hast stol'n away from fairy land",
        "And in the shape of Corin sat all day",
        "Playing on pipes of corn , and versing love",
        "To amorous Phillida . Why art thou here",
        "Come from the furthest steppe of India ?",
        "But that , forsooth , the bouncing Amazon",
        "Your buskin'd mistress and your warrior love",
        "To Theseus must be wedded , and you come",
        "To give their bed joy and prosperity",
        "How canst thou thus for shame , Titania",
        "Glance at my credit with Hippolyta",
        "Knowing I know thy love to Theseus ?",
        "Didst thou not lead him through the glimmering night",
        "From Perigouna , whom he ravished ?",
        "And make him with fair  gle break his faith",
        "With Ariadne , and Antiopa ?",
        "These are the forgeries of jealousy :",
        "And never , since the middle summer's spring",
        "Met we on hill , in dale , forest , or mead",
        "By paved fountain , or by rushy brook",
        "Or in the beached margent of the sea",
        "To dance our ringlets to the whistling wind",
        "But with thy brawls thou hast disturb'd our sport",
        "Therefore the winds , piping to us in vain",
        "As in revenge , have suck'd up from the sea",
        "Contagious fogs ; which , falling in the land",
        "Have every pelting river made so proud",
        "That they have overborne their continents :",
        "The ox hath therefore stretch'd his yoke in vain",
        "The ploughman lost his sweat , and the green corn",
        "Hath rotted ere his youth attain'd a beard :",
        "The fold stands empty in the drowned field",
        "And crows are fatted with the murrion flock",
        "The nine men's morris is fill'd up with mud",
        "And the quaint mazes in the wanton green",
        "For lack of tread are undistinguishable :",
        "The human mortals want their winter here :",
        "No night is now with hymn or carol blest :",
        "Therefore the moon , the governess of floods",
        "Pale in her anger , washes all the air",
        "That rheumatic diseases do abound :",
        "And thorough this distemperature we see",
        "The seasons alter : hoary-headed frosts",
        "Fall in the fresh lap of the crimson rose",
        "And on old Hiems' thin and icy crown",
        "An odorous chaplet of sweet summer buds",
        "Is , as in mockery , set . The spring , the summer",
        "The childing autumn , angry winter , change",
        "Their wonted liveries , and the mazed world",
        "By their increase , now knows not which is which",
        "And this same progeny of evil comes",
        "From our debate , from our dissension :",
        "We are their parents and original",
        "Do you amend it then ; it lies in you",
        "Why should Titania cross her Oberon ?",
        "I do but beg a little changeling boy",
        "To be my henchman",
        "Set your heart at rest",
        "The fairy land buys not the child of me",
        "His mother was a votaress of my order :",
        "And , in the spiced Indian air , by night",
        "Full often hath she gossip'd by my side",
        "And sat with me on Neptune's yellow sands",
        "Marking the embarked traders on the flood",
        "When we have laugh'd to see the sails conceive",
        "And grow big-bellied with the wanton wind",
        "Which she , with pretty and with swimming gait",
        "Following ,her womb then rich with my young squire",
        "Would imitate , and sail upon the land",
        "To fetch me trifles , and return again",
        "As from a voyage , rich with merchandise",
        "But she , being mortal , of that boy did die",
        "And for her sake I do rear up her boy",
        "And for her sake I will not part with him",
        "How long within this wood intend you stay ?",
        "Perchance , till after Theseus' weddingday",
        "If you will patiently dance in our round",
        "And see our moonlight revels , go with us",
        "If not , shun me , and I will spare your haunts",
        "Give me that boy , and I will go with thee",
        "Not for thy fairy kingdom . Fairies , away !",
        "We shall chide downright , if I longer stay",
        "Well , go thy way : thou shalt not from this grove",
        "Till I torment thee for this injury",
        "My gentle Puck , come hither . Thou remember'st",
        "Since once I sat upon a promontory",
        "And heard a mermaid on a dolphin's back",
        "Uttering such dulcet and harmonious breath",
        "That the rude sea grew civil at her song",
        "And certain stars shot madly from their spheres",
        "To hear the sea-maid's music",
        "I remember",
        "That very time I saw , but thou couldst not",
        "Flying between the cold moon and the earth",
        "Cupid all arm'd : a certain aim he took",
        "At a fair vestal throned by the west",
        "And loos'd his love-shaft smartly from his bow",
        "As it should pierce a hundred thousand hearts",
        "But I might see young Cupid's fiery shaft",
        "Quench'd in the chaste beams of the wat'ry moon",
        "And the imperial votaress passed on",
        "In maiden meditation , fancy-free",
        "Yet mark'd I where the bolt of Cupid fell :",
        "It fell upon a little western flower",
        "Before milk-white , now purple with love's wound",
        "And maidens call it , Love-in-idleness",
        "Fetch me that flower ; the herb I show'd thee once :",
        "The juice of it on sleeping eyelids laid",
        "Will make or man or woman madly dote",
        "Upon the next live creature that it sees",
        "Fetch me this herb ; and be thou here again",
        "Ere the leviathan can swim a league",
        "I'll put a girdle round about the earth",
        "In forty minutes",
        "Having once this juice",
        "I'll watch Titania when she is asleep",
        "And drop the liquor of it in her eyes :",
        "The next thing then she waking looks upon",
        "Be it on lion , bear , or wolf , or bull",
        "On meddling monkey , or on busy ape",
        "She shall pursue it with the soul of love :",
        "And ere I take this charm off from her sight",
        "As I can take it with another herb",
        "I'll make her render up her page to me",
        "But who comes here ? I am invisible",
        "And I will overhear their conference",
        "I love thee not , therefore pursue me not",
        "Where is Lysander and fair Hermia ?",
        "The one I'll slay , the other slayeth me",
        "Thou told'st me they were stol'n into this wood",
        "And here am I , and wood within this wood",
        "Because I cannot meet my Hermia",
        "Hence ! get thee gone , and follow me no more",
        "You draw me , you hard-hearted adamant :",
        "But yet you draw not iron , for my heart",
        "Is true as steel : leave you your power to draw",
        "And I shall have no power to follow you",
        "Do I entice you ? Do I speak you fair ?",
        "Or , rather , do I not in plainest truth",
        "Tell you I do not nor I cannot love you ?",
        "And even for that do I love you the more",
        "I am your spaniel ; and , Demetrius",
        "The more you beat me , I will fawn on you :",
        "Use me but as your spaniel , spurn me , strike me",
        "Neglect me , lose me ; only give me leave",
        "Unworthy as I am , to follow you",
        "What worser place can I beg in your love",
        "And yet a place of high respect with me",
        "Than to be used as you use your dog ?",
        "Tempt not too much the hatred of my spirit",
        "For I am sick when I do look on you",
        "And I am sick when I look not on you",
        "You do impeach your modesty too much",
        "To leave the city , and commit yourself",
        "Into the hands of one that loves you not",
        "To trust the opportunity of night",
        "And the ill counsel of a desert place",
        "With the rich worth of your virginity",
        "Your virtue is my privilege : for that",
        "It is not night when I do see your face",
        "Therefore I think I am not in the night",
        "Nor doth this wood lack worlds of company",
        "For you in my respect are all the world :",
        "Then how can it be said I am alone",
        "When all the world is here to look on me ?",
        "I'll run from thee and hide me in the brakes",
        "And leave thee to the mercy of wild beasts",
        "The wildest hath not such a heart as you",
        "Run when you will , the story shall be chang'd",
        "Apollo flies , and Daphne holds the chase",
        "The dove pursues the griffin ; the mild hind",
        "Makes speed to catch the tiger : bootless speed",
        "When cowardice pursues and valour flies",
        "I will not stay thy questions : let me go",
        "Or , if thou follow me , do not believe",
        "But I shall do thee mischief in the wood",
        "Ay , in the temple , in the town , the field",
        "You do me mischief . Fie , Demetrius !",
        "Your wrongs do set a scandal on my sex",
        "We cannot fight for love , as men may do",
        "We should be woo'd and were not made to woo",
        "I'll follow thee and make a heaven of hell",
        "To die upon the hand I love so well",
        "Fare thee well , nymph : ere he do leave this grove",
        "Thou shalt fly him , and he shall seek thy love",
        "Hast thou the flower there ? Welcome , wanderer",
        "Ay , there it is",
        "I pray thee , give it me",
        "I know a bank whereon the wild thyme blows",
        "Where oxlips and the nodding violet grows",
        "Quite over-canopied with luscious woodbine",
        "With sweet musk-roses , and with eglantine :",
        "There sleeps Titania some time of the night",
        "Lull'd in these flowers with dances and delight",
        "And there the snake throws her enamell'd skin",
        "Weed wide enough to wrap a fairy in :",
        "And with the juice of this I'll streak her eyes",
        "And make her full of hateful fantasies",
        "Take thou some of it , and seek through this grove :",
        "A sweet Athenian lady is in love",
        "With a disdainful youth : anoint his eyes",
        "But do it when the next thing he espies",
        "May be the lady . Thou shalt know the man",
        "By the Athenian garments he hath on",
        "Effect it with some care , that he may prove",
        "More fond on her than she upon her love",
        "And look thou meet me ere the first cock crow",
        "Fear not , my lord , your servant shall do so",
        "Come , now a roundel and a fairy song",
        "Then , for the third of a minute , hence",
        "Some to kill cankers in the musk-rose buds",
        "Some war with rere-mice for their leathern wings",
        "To make my small elves coats , and some keep back",
        "The clamorous owl , that nightly hoots , and wonders",
        "At our quaint spirits . Sing me now asleep",
        "Then to your offices , and let me rest",
        "The Fairies sing",
        "I",
        "You spotted snakes with double tongue",
        "Thorny hedge-hogs , be not seen",
        "Newts , and blind-worms , do no wrong",
        "Come not near our fairy queen",
        "Philomel , with melody",
        "Sing in our sweet lullaby :",
        "Lulla , lulla , lullaby ; lulla , lulla , lullaby :",
        "Never harm",
        "Nor spell , nor charm",
        "Come our lovely lady nigh",
        "So , good night , with lullaby",
        "II",
        "Weaving spiders come not here",
        "Hence , you long-legg'd spinners , hence !",
        "Beetles black , approach not near",
        "Worm nor snail , do no offence",
        "Philomel , with melody ,  &c",
        "Hence , away ! now all is well",
        "One aloof stand sentinel",
        "What thou seest when thou dost wake",
        "Do it for thy true-love take",
        "Love and languish for his sake :",
        "Be it ounce , or cat , or bear",
        "Pard , or boar with bristled hair",
        "In thy eye that shall appear",
        "When thou wak'st , it is thy dear",
        "Wake when some vile thing is near",
        "Fair love , you faint with wandering in the wood",
        "And to speak troth , I have forgot our way :",
        "We'll rest us , Hermia , if you think it good",
        "And tarry for the comfort of the day",
        "Be it so , Lysander : find you out a bed",
        "For I upon this bank will rest my head",
        "One turf shall serve as pillow for us both",
        "One heart , one bed , two bosoms , and one troth",
        "Nay , good Lysander ; for my sake , my dear",
        "Lie further off yet , do not lie so near",
        "O ! take the sense , sweet , of my innocence",
        "Love takes the meaning in love's conference",
        "I mean that my heart unto yours is knit",
        "So that but one heart we can make of it",
        "Two bosoms interchained with an oath",
        "So then two bosoms and a single troth",
        "Then by your side no bed-room me deny",
        "For , lying so , Hermia , I do not lie",
        "Lysander riddles very prettily :",
        "Now much beshrew my manners and my pride",
        "If Hermia meant to say Lysander lied",
        "But , gentle friend , for love and courtesy",
        "Lie further off ; in human modesty",
        "Such separation as may well be said",
        "Becomes a virtuous bachelor and a maid",
        "So far be distant ; and , good night , sweet friend",
        "Thy love ne'er alter till thy sweet life end !",
        "Amen , amen , to that fair prayer , say I",
        "And then end life when I end loyalty !",
        "Here is my bed : sleep give thee all his rest !",
        "With half that wish the wisher's eyes be press'd !",
        "Through the forest have I gone",
        "But Athenian found I none",
        "On whose eyes I might approve",
        "This flower's force in stirring love",
        "Night and silence ! who is here ?",
        "Weeds of Athens he doth wear :",
        "This is he , my master said",
        "Despised the Athenian maid",
        "And here the maiden , sleeping sound",
        "On the dank and dirty ground",
        "Pretty soul ! she durst not lie",
        "Near this lack-love , this kill-courtesy",
        "Churl , upon thy eyes I throw",
        "All the power this charm doth owe",
        "When thou wak'st , let love forbid",
        "Sleep his seat on thy eyelid :",
        "So awake when I am gone",
        "For I must now to Oberon",
        "Stay , though thou kill me , sweet Demetrius",
        "I charge thee , hence , and do not haunt me thus",
        "O ! wilt thou darkling leave me ? do not so",
        "Stay , on thy peril : I alone will go",
        "O ! I am out of breath in this fond chase",
        "The more my prayer , the lesser is my grace",
        "Happy is Hermia , wheresoe'er she lies",
        "For she hath blessed and attractive eyes",
        "How came her eyes so bright ? Not with salt tears :",
        "If so , my eyes are oftener wash'd than hers",
        "No , no , I am as ugly as a bear",
        "For beasts that meet me run away for fear",
        "Therefore no marvel though Demetrius",
        "Do , as a monster , fly my presence thus",
        "What wicked and dissembling glass of mine",
        "Made me compare with Hermia's sphery eyne ?",
        "But who is here ? Lysander ! on the ground !",
        "Dead ? or asleep ? I see no blood , no wound",
        "Lysander , if you live , good sir , awake",
        "And run through fire I will for thy sweet sake",
        "Transparent Helena ! Nature shows art",
        "That through thy bosom makes me see thy heart",
        "Where is Demetrius ? O ! how fit a word",
        "Is that vile name to perish on my sword",
        "Do not say so , Lysander ; say not so",
        "What though he love your Hermia ? Lord ! what though ?",
        "Yet Hermia still loves you : then be content",
        "Content with Hermia ! No : I do repent",
        "The tedious minutes I with her have spent",
        "Not Hermia , but Helena I love :",
        "Who will not change a raven for a dove ?",
        "The will of man is by his reason sway'd",
        "And reason says you are the worthier maid",
        "Things growing are not ripe until their season",
        "So I , being young , till now ripe not to reason",
        "And touching now the point of human skill",
        "Reason becomes the marshal to my will",
        "And leads me to your eyes ; where I o'erlook",
        "Love's stories written in love's richest book",
        "Wherefore was I to this keen mockery born ?",
        "When at your hands did I deserve this scorn ?",
        "Is't not enough , is't not enough , young man",
        "That I did never , no , nor never can",
        "Deserve a sweet look from Demetrius' eye",
        "But you must flout my insufficiency ?",
        "Good troth , you do me wrong , good sooth , you do",
        "In such disdainful manner me to woo",
        "But fare you well : perforce I must confess",
        "I thought you lord of more true gentleness",
        "O ! that a lady of one man refus'd",
        "Should of another therefore be abus'd",
        "She sees not Hermia . Hermia , sleep thou there",
        "And never mayst thou come Lysander near",
        "For , as a surfeit of the sweetest things",
        "The deepest loathing to the stomach brings",
        "Or , as the heresies that men do leave",
        "Are hated most of those they did deceive :",
        "So thou , my surfeit and my heresy",
        "Of all be hated , but the most of me !",
        "And , all my powers , address your love and might",
        "To honour Helen , and to be her knight",
        "Help me , Lysander , help me ! do thy best",
        "To pluck this crawling serpent from my breast",
        "Ay me , for pity ! what a dream was here !",
        "Lysander , look how I do quake with fear :",
        "Methought a serpent eat my heart away",
        "And you sat smiling at his cruel prey",
        "Lysander ! what ! remov'd ?Lysander ! lord !",
        "What ! out of hearing ? gone ? no sound , no word ?",
        "Alack ! where are you ? speak , an if you hear",
        "Speak , of all loves ! I swound almost with fear",
        "No ! then I well perceive you are not nigh :",
        "Either death or you I'll find immediately",
        "Are we all met ?",
        "Pat , pat ; and here's a marvellous convenient place for our rehearsal . This green plot shall be our stage , this hawthorn-brake our tiring-house ; and we will do it in action as we will do it before the duke",
        "Peter Quince",
        "What sayst thou , bully Bottom ?",
        "There are things in this comedy of Pyramus and Thisby that will never please . First , Pyramus must draw a sword to kill himself , which the ladies cannot abide . How answer you that ?",
        "By'r lakin , a parlous fear",
        "I believe we must leave the killing out , when all is done",
        "Not a whit : I have a device to make all well . Write me a prologue ; and let the prologue seem to say , we will do no harm with our swords , and that Pyramus is not killed indeed ; and , for the more better assurance , tell them that I , Pyramus , am not Pyramus , but Bottom the weaver : this will put them out of fear",
        "Well , we will have such a prologue , and it shall be written in eight and six",
        "No , make it two more : let it be written in eight and eight",
        "Will not the ladies be afeard of the lion ?",
        "I fear it , I promise you",
        "Masters , you ought to consider with yourselves : to bring in ,God shield us !a lion among ladies , is a most dreadful thing ; for there is not a more fearful wild-fowl than your lion living , and we ought to look to it",
        "Therefore , another prologue must tell he is not a lion",
        "Nay , you must name his name , and half his face must be seen through the lion's neck ; and he himself must speak through , saying thus , or to the same defect , 'Ladies ,' or , 'Fair ladies ,' 'I would wish you ,' or , 'I would request you ,' or , 'I would entreat you , not to fear , not to tremble : my life for yours . If you think I come hither as a lion , it were pity of my life : no , I am no such thing : I am a man as other men are ;' and there indeed let him name his name , and tell them plainly he is Snug the joiner",
        "Well , it shall be so . But there is two hard things , that is , to bring the moonlight into a chamber ; for , you know , Pyramus and Thisby meet by moonlight",
        "Doth the moon shine that night we play our play ?",
        "A calendar , a calendar ! look in the almanack ; find out moonshine , find out moonshine",
        "Yes , it doth shine that night",
        "Why , then may you leave a casement of the great chamber-window , where we play , open ; and the moon may shine in at the casement",
        "Ay ; or else one must come in with a bush of thorns and a lanthorn , and say he comes to disfigure , or to present , the person of Moonshine . Then , there is another thing : we must have a wall in the great chamber ; for Pyramus and Thisby , says the story , did talk through the chink of a wall",
        "You can never bring in a wall . What say you , Bottom ?",
        "Some man or other must present Wall ; and let him have some plaster , or some loam , or some rough-cast about him , to signify wall ; and let him hold his fingers thus , and through that cranny shall Pyramus and Thisby whisper",
        "If that may be , than all is well . Come , sit down , every mother's son , and rehearse your parts . Pyramus , you begin : when you have spoken your speech , enter into that brake ; and so every one according to his cue",
        "What hempen home-spuns have we swaggering here",
        "So near the cradle of the fairy queen ?",
        "What ! a play toward ; I'll be an auditor",
        "An actor too perhaps , if I see cause",
        "Speak , Pyramus .Thisby , stand forth",
        "Thisby , the flowers have odious savours sweet",
        "Odorous , odorous",
        "odours savours sweet :",
        "So hath thy breath , my dearest Thisby dear . But hark , a voice ! stay thou but here awhile",
        "And by and by I will to thee appear",
        "A stranger Pyramus than e'er play'd here !",
        "Must I speak now ?",
        "Ay , marry , must you ; for you must understand , he goes but to see a noise that he heard , and is to come again",
        "Most radiant Pyramus , most lily-white of hue",
        "Of colour like the red rose on triumphant brier",
        "Most brisky juvenal , and eke most lovely Jew",
        "As true as truest horse that yet would never tire",
        "I'll meet thee , Pyramus , at Ninny's tomb",
        "'Ninus' tomb ,' man . Why , you must not speak that yet ; that you answer to Pyramus : you speak all your part at once , cues and all . Pyramus , enter : your cue is past ; it is 'never tire .'",
        "O !As true as truest horse , that yet would never tire",
        "If I were , fair Thisby , I were only thine",
        "O monstrous ! O strange ! we are haunted",
        "Pray , masters ! fly , masters !Help !",
        "I'll follow you , I'll lead you about a round",
        "Through bog , through bush , through brake , through brier :",
        "Sometime a horse I'll be , sometime a hound",
        "A hog , a headless bear , sometime a fire",
        "And neigh , and bark , and grunt , and roar , and burn",
        "Like horse , hound , hog , bear , fire , at every turn",
        "Why do they run away ? this is a knavery of them to make me afeard",
        "O Bottom , thou art changed ! what do I see on thee ?",
        "What do you see ? you see an ass-head of your own , do you ?",
        "Bless thee , Bottom ! bless thee ! thou art translated",
        "I see their knavery : this is to make an ass of me ; to fright me , if they could . But I will not stir from this place , do what they can : I will walk up and down here , and I will sing , that they shall hear I am not afraid",
        "The ousel-cock , so black of hue",
        "With orange-tawny bill",
        "The throstle with his note so true",
        "The wren with little quill",
        "What angel wakes me from my flowery bed ?",
        "The finch , the sparrow , and the lark",
        "The plain-song cuckoo gray",
        "Whose note full many a man doth mark",
        "And dares not answer , nay",
        "for indeed , who would set his wit to so foolish a bird ? who would give a bird the lie , though he cry 'cuckoo' never so ?",
        "I pray thee , gentle mortal , sing again :",
        "Mine ear is much enamour'd of thy note",
        "So is mine eye enthralled to thy shape",
        "And thy fair virtue's force , perforce , doth move me",
        "On the first view , to say , to swear , I love thee",
        "Methinks , mistress , you should have little reason for that : and yet , to say the truth , reason and love keep little company together now-a-days . The more the pity , that some honest neighbours will not make them friends . Nay , I can gleek upon occasion",
        "Thou art as wise as thou art beautiful",
        "Not so , neither ; but if I had wit enough to get out of this wood , I have enough to serve mine own turn",
        "Out of this wood do not desire to go :",
        "Thou shalt remain here , whe'r thou wilt or no",
        "I am a spirit of no common rate",
        "The summer still doth tend upon my state",
        "And I do love thee : therefore , go with me",
        "I'll give thee fairies to attend on thee",
        "And they shall fetch thee jewels from the deep",
        "And sing , while thou on pressed flowers dost sleep :",
        "And I will purge thy mortal grossness so",
        "That thou shalt like an airy spirit go",
        "Pease-blossom ! Cobweb ! Moth ! and Mustardseed !",
        "Ready",
        "And I",
        "And I",
        "And I",
        "Where shall we go ?",
        "Be kind and courteous to this gentleman",
        "Hop in his walks , and gambol in his eyes",
        "Feed him with apricocks and dewberries",
        "With purple grapes , green figs , and mulberries",
        "The honey-bags steal from the humble-bees",
        "And for night-tapers crop their waxen thighs",
        "And light them at the fiery glow-worm's eyes",
        "To have my love to bed , and to arise",
        "And pluck the wings from painted butterflies",
        "To fan the moonbeams from his sleeping eyes :",
        "Nod to him , elves , and do him courtesies",
        "Hail , mortal !",
        "Hail !",
        "Hail !",
        "Hail !",
        "I cry your worships mercy , heartily : I beseech your worship's name",
        "Cobweb",
        "I shall desire you of more acquaintance , good Master Cobweb : if I out my finger , I shall make bold with you . Your name , honest gentleman ?",
        "Pease-blossom",
        "I pray you , commend me to Mistress Squash , your mother , and to Master Peascod , your father . Good Master Pease-blossom , I shall desire you of more acquaintance too . Your name , I beseech you , sir ?",
        "Mustard-seed",
        "Good Master Mustard-seed , I know your patience well : that same cowardly , giant-like ox-beef hath devoured many a gentleman of your house . I promise you , your kindred hath made my eyes water ere now . I desire you of more acquaintance , good Master Mustard-seed",
        "Come , wait upon him ; lead him to my bower",
        "The moon methinks , looks with a watery eye",
        "And when she weeps , weeps every little flower",
        "Lamenting some enforced chastity",
        "Tie up my love's tongue , bring him silently",
        "I wonder if Titania be awak'd",
        "Then , what it was that next came in her eye",
        "Which she must dote on in extremity",
        "Here comes my messenger",
        "How now , mad spirit !",
        "What night-rule now about this haunted grove ?",
        "My mistress with a monster is in love",
        "Near to her close and consecrated bower",
        "While she was in her dull and sleeping hour",
        "A crew of patches , rude mechanicals",
        "That work for bread upon Athenian stalls",
        "Were met together to rehearse a play",
        "Intended for great Theseus' nuptial day",
        "The shallowest thick-skin of that barren sort",
        "Who Pyramus presented in their sport",
        "Forsook his scene , and enter'd in a brake",
        "When I did him at this advantage take",
        "An ass's nowl I fixed on his head :",
        "Anon his Thisbe must be answered",
        "And forth my mimick comes . When they him spy",
        "As wild geese that the creeping fowler eye",
        "Or russet-pated choughs , many in sort",
        "Rising and cawing at the gun's report",
        "Sever themselves , and madly sweep the sky",
        "So , at his sight , away his fellows fly",
        "And , at our stamp , here o'er and o'er one falls",
        "He murder cries , and help from Athens calls",
        "Their sense thus weak , lost with their fears thus strong",
        "Made senseless things begin to do them wrong",
        "For briers and thorns at their apparel snatch",
        "Some sleeves , some hats , from yielders all things catch",
        "I led them on in this distracted fear",
        "And left sweet Pyramus translated there",
        "When in that moment , so it came to pass",
        "Titania wak'd and straightway lov'd an ass",
        "This falls out better than I could devise",
        "But hast thou yet latch'd the Athenian's eyes",
        "With the love-juice , as I did bid thee do ?",
        "I took him sleeping ,that is finish'd too",
        "And the Athenian woman by his side",
        "That , when he wak'd , of force she must be ey'd",
        "Stand close : this is the same Athenian",
        "This is the woman ; but not this the man",
        "O ! why rebuke you him that loves you so ?",
        "Lay breath so bitter on your bitter foe",
        "Now I but chide ; but I should use thee worse",
        "For thou , I fear , hast given me cause to curse",
        "If thou hast slain Lysander in his sleep",
        "Being o'er shoes in blood , plunge in knee deep",
        "And kill me too",
        "The sun was not so true unto the day",
        "As he to me . Would he have stol'n away",
        "From sleeping Hermia ? I'll believe as soon",
        "This whole earth may be bor'd , and that the moon",
        "May through the centre creep , and so displease",
        "Her brother's noontide with the Antipodes",
        "It cannot be but thou hast murder'd him",
        "So should a murderer look , so dead , so grim",
        "So should the murder'd look , and so should I",
        "Pierc'd through the heart with your stern cruelty",
        "Yet you , the murderer , look as bright , as clear",
        "As yonder Venus in her glimmering sphere",
        "What's this to my Lysander ? where is he ?",
        "Ah ! good Demetrius , wilt thou give him me ?",
        "I had rather give his carcass to my hounds",
        "Out , dog ! out , cur ! thou driv'st me past the bounds",
        "Of maiden's patience . Hast thou slain him then ?",
        "Henceforth be never number'd among men !",
        "O ! once tell true , tell true , e'en for my sake",
        "Durst thou have look'd upon him being awake",
        "And hast thou kill'd him sleeping ? O brave touch !",
        "Could not a worm , an adder , do so much ?",
        "An adder did it ; for with doubler tongue",
        "Than thine , thou serpent , never adder stung",
        "You spend your passion on a mispris'd mood :",
        "I am not guilty of Lysander's blood",
        "Nor is he dead , for aught that I can tell",
        "I pray thee , tell me then that he is well",
        "An if I could , what should I get therefore ?",
        "A privilege never to see me more",
        "And from thy hated presence part I so",
        "See me no more , whe'r he be dead or no",
        "There is no following her in this fierce vein :",
        "Here therefore for awhile I will remain",
        "So sorrow's heaviness doth heavier grow",
        "For debt that bankrupt sleep doth sorrow owe",
        "Which now in some slight measure it will pay",
        "If for his tender here I make some stay",
        "What hast thou done ? thou hast mistaken quite",
        "And laid the love-juice on some true-love's sight :",
        "Of thy misprision must perforce ensue",
        "Some true-love turn'd , and not a false turn'd true",
        "Then fate o'er-rules , that , one man holding troth",
        "A million fail , confounding oath on oath",
        "About the wood go swifter than the wind",
        "And Helena of Athens look thou find :",
        "All fancy-sick she is , and pale of cheer",
        "With sighs of love , that cost the fresh blood dear",
        "By some illusion see thou bring her here :",
        "I'll charm his eyes against she do appear",
        "I go , I go ; look how I go",
        "Swifter than arrow from the Tartar's bow",
        "Flower of this purple dye",
        "Hit with Cupid's archery",
        "Sink in apple of his eye",
        "When his love he doth espy",
        "Let her shine as gloriously",
        "As the Venus of the sky",
        "When thou wak'st , if she be by",
        "Beg of her for remedy",
        "Captain of our fairy band",
        "Helena is here at hand",
        "And the youth , mistook by me",
        "Pleading for a lover's fee",
        "Shall we their fond pageant see ?",
        "Lord , what fools these mortals be !",
        "Stand aside : the noise they make",
        "Will cause Demetrius to awake",
        "Then will two at once woo one",
        "That must needs be sport alone",
        "And those things do best please me",
        "That befall preposterously",
        "Why should you think that I should woo in scorn ?",
        "Scorn and derision never come in tears :",
        "Look , when I vow , I weep ; and vows so born",
        "In their nativity all truth appears",
        "How can these things in me seem scorn to you",
        "Bearing the badge of faith to prove them true ?",
        "You do advance your cunning more and more",
        "When truth kills truth , O devilish-holy fray !",
        "These vows are Hermia's : will you give her o'er ?",
        "Weigh oath with oath , and you will nothing weigh :",
        "Your vows , to her and me , put in two scales",
        "Will even weigh , and both as light as tales",
        "I had no judgment when to her I swore",
        "Nor none , in my mind , now you give her o'er",
        "Demetrius loves her , and he loves not you",
        "O Helen ! goddess , nymph , perfect , divine !",
        "To what , my love , shall I compare thine eyne ?",
        "Crystal is muddy . O ! how ripe in show",
        "Thy lips , those kissing cherries , tempting grow",
        "This pure congealed white , high Taurus' snow",
        "Fann'd with the eastern wind , turns to a crow",
        "When thou hold'st up thy hand . O ! let me kiss "
    ]

    words = [
        'understandings', 'understanding', 'conversations', 'disappearing', 'informations', 'grandmothers',
        'grandfathers', 'questionings', 'conversation', 'information', 'approaching', 'understands', 'immediately',
        'positioning', 'questioning', 'grandmother', 'travellings', 'questioners', 'recognizing', 'recognizers',
        'televisions', 'remembering', 'rememberers', 'expressions', 'discovering', 'disappeared', 'interesting',
        'grandfather', 'straightest', 'controllers', 'controlling', 'considering', 'remembered', 'cigarettes',
        'companying', 'completely', 'spreadings', 'considered', 'continuing', 'controlled', 'stationing', 'controller',
        'straighter', 'stretching', 'businesses', 'somebodies', 'soldiering', 'countering', 'darknesses', 'situations',
        'directions', 'disappears', 'younglings', 'suggesting', 'afternoons', 'breathings', 'distancing', 'screenings',
        'schoolings', 'especially', 'everything', 'everywhere', 'explaining', 'explainers', 'expression', 'branchings',
        'revealings', 'repeatings', 'surprising', 'rememberer', 'somewheres', 'television', 'themselves', 'recognizer',
        'recognizes', 'recognized', 'belongings', 'finishings', 'travelling', 'questioner', 'beginnings', 'travelings',
        'questioned', 'followings', 'pretending', 'forgetting', 'forgetters', 'forwarding', 'positioned', 'travellers',
        'gatherings', 'perfecting', 'understand', 'understood', 'weightings', 'approaches', 'officering', 'numberings',
        'happenings', 'mentioning', 'letterings', 'husbanding', 'imaginings', 'approached', 'apartments', 'whispering',
        'interested', 'discovered', 'spinnings', 'clearings', 'climbings', 'spendings', 'clothings', 'colorings',
        'soundings', 'truckings', 'somewhere', 'troubling', 'companies', 'companied', 'beautiful', 'computers',
        'confusing', 'considers', 'travelers', 'youngling', 'continues', 'continued', 'traveller', 'traveling',
        'yellowing', 'apartment', 'beginning', 'wheelings', 'travelled', 'sometimes', 'something', 'appearing',
        'cornering', 'believing', 'countered', 'believers', 'countries', 'soldiered', 'coverings', 'creatures',
        'crossings', 'accepting', 'daughters', 'belonging', 'situation', 'silvering', 'different', 'silencing',
        'touchings', 'bettering', 'tomorrows', 'disappear', 'thinkings', 'boardings', 'discovers', 'admitting',
        'wrappings', 'distances', 'distanced', 'sightings', 'shrugging', 'doctoring', 'showering', 'shoulders',
        'shoppings', 'shootings', 'dressings', 'sheetings', 'shadowing', 'settlings', 'servicing', 'seriously',
        'seconding', 'searching', 'weighting', 'screening', 'screaming', 'schooling', 'teachings', 'bothering',
        'everybody', 'botherers', 'bottoming', 'excepting', 'expecting', 'explained', 'direction', 'explainer',
        'surprised', 'surprises', 'waterings', 'branching', 'revealing', 'returning', 'surfacing', 'familiars',
        'repeating', 'fathering', 'reminding', 'supposing', 'breasting', 'attacking', 'remembers', 'breathing',
        'remaining', 'breathers', 'brightest', 'brownings', 'suggested', 'recognize', 'fightings', 'attention',
        'figurings', 'receiving', 'reasoning', 'realizing', 'fingering', 'buildings', 'finishing', 'stupidest',
        'stuffings', 'questions', 'watchings', 'flashings', 'strongest', 'strikings', 'flighting', 'flowering',
        'promisers', 'promising', 'following', 'bathrooms', 'prettiest', 'pretended', 'stretched', 'foreheads',
        'foresting', 'stretches', 'forgotten', 'pressings', 'forgetter', 'strangest', 'preparing', 'forwarded',
        'strangers', 'possibles', 'positions', 'afternoon', 'straights', 'pocketing', 'gardening', 'pleasings',
        'wondering', 'gathering', 'picturing', 'personals', 'perfected', 'stomaches', 'stomached', 'carefully',
        'stationed', 'catchings', 'parenting', 'paintings', 'orderings', 'groupings', 'wintering', 'officered',
        'offerings', 'centering', 'numbering', 'neighbors', 'certainly', 'happening', 'narrowing', 'narrowest',
        'mountains', 'mothering', 'mirroring', 'middlings', 'messaging', 'standings', 'mentioned', 'mattering',
        'marriages', 'histories', 'machining', 'hospitals', 'listening', 'lightings', 'springing', 'lettering',
        'husbanded', 'spreaders', 'whispered', 'imagining', 'imaginers', 'spreading', 'important', 'languages',
        'answering', 'cigarette', 'interests', 'spiriting', 'cleanings', 'knockings', 'soundest', 'coatings',
        'sounders', 'sounding', 'colleges', 'coloring', 'colorful', 'wouldnt', 'training', 'colorers', 'sorriest',
        'worrying', 'belonged', 'approach', 'tracking', 'touchers', 'touching', 'computer', 'whatever', 'toppings',
        'confused', 'confuses', 'workings', 'consider', 'bettered', 'teething', 'tonights', 'tonguers', 'tonguing',
        'continue', 'arriving', 'tomorrow', 'controls', 'together', 'blacking', 'blackest', 'throwers', 'blocking',
        'throwing', 'coolings', 'someones', 'blockers', 'somebody', 'thirties', 'soldiers', 'cornered', 'weighted',
        'counting', 'thoughts', 'counters', 'thinking', 'thinners', 'thinning', 'coursing', 'covering', 'thinnest',
        'craziest', 'snapping', 'creating', 'creature', 'thickest', 'boarding', 'crossing', 'smokings', 'crowding',
        'smelling', 'smallest', 'cuttings', 'slipping', 'slightly', 'dancings', 'sleepers', 'sleeping', 'slamming',
        'wordings', 'darkness', 'daughter', 'boatings', 'skinning', 'weddings', 'thanking', 'sittings', 'deciding',
        'deciders', 'singling', 'singings', 'despites', 'simplest', 'terrible', 'silvered', 'tellings', 'wearings',
        'youngest', 'watering', 'silences', 'teachers', 'bookings', 'agreeing', 'teaching', 'discover', 'attacked',
        'bothered', 'botherer', 'watching', 'swingers', 'bottling', 'distance', 'silenced', 'signings', 'bottomed',
        'sighting', 'shutting', 'shrugged', 'wondered', 'swinging', 'doctored', 'sweetest', 'showered', 'showings',
        'doorways', 'shouting', 'shoulder', 'wronging', 'shortest', 'surprise', 'dragging', 'shopping', 'shooters',
        'drawings', 'actually', 'shooting', 'dreaming', 'dressing', 'avoiding', 'shitting', 'shirting', 'shipping',
        'drinking', 'drinkers', 'braining', 'sheeting', 'sharpest', 'drivings', 'sharpers', 'dropping', 'droppers',
        'shadowed', 'surfaced', 'settling', 'washings', 'settings', 'services', 'serviced', 'earliest', 'backings',
        'earthing', 'servings', 'branches', 'branched', 'seconded', 'seatings', 'surfaces', 'searched', 'searches',
        'walkings', 'screened', 'waitings', 'screamed', 'supposed', 'emptiest', 'emptying', 'breaking', 'breakers',
        'schooled', 'enjoying', 'enjoyers', 'entering', 'runnings', 'breasted', 'rounders', 'rounding', 'supposes',
        'everyone', 'visitors', 'visiting', 'breathed', 'excepted', 'roofings', 'exciting', 'breathes', 'expected',
        'rollings', 'bankings', 'breather', 'explains', 'villages', 'bridging', 'viewings', 'brighter', 'ringings',
        'righting', 'suitings', 'bringing', 'revealed', 'bringers', 'returned', 'failings', 'repliers', 'replying',
        'repeated', 'brothers', 'familiar', 'wintered', 'families', 'suggests', 'farthest', 'furthest', 'browning',
        'fathered', 'removing', 'building', 'reminded', 'bathroom', 'allowing', 'suddenly', 'remember', 'allowers',
        'feedings', 'builders', 'burnings', 'feelings', 'remained', 'refusing', 'stupider', 'windings', 'although',
        'stuffing', 'studying', 'business', 'angriest', 'fighting', 'fighters', 'students', 'figuring', 'received',
        'twenties', 'receives', 'fillings', 'reasoned', 'findings', 'stronger', 'turnings', 'realizes', 'realized',
        'readiest', 'fingered', 'readying', 'striking', 'trusters', 'finishes', 'trusting', 'finished', 'readings',
        'reachers', 'reaching', 'quieters', 'quietest', 'quieting', 'fittings', 'quickest', 'writings', 'beaching',
        'question', 'trucking', 'callings', 'stranger', 'flashing', 'beatings', 'answered', 'flattest', 'flatting',
        'flighted', 'straight', 'troubled', 'flowered', 'pullings', 'storming', 'promiser', 'couldnt', 'promised',
        'promises', 'couldn’t', 'followed', 'stoppers', 'problems', 'probably', 'prettier', 'stopping', 'pretends',
        'stomachs', 'troubles', 'pressers', 'tripping', 'forehead', 'stickers', 'forested', 'pressing', 'whispers',
        'carrying', 'sticking', 'carriers', 'stepping', 'stealers', 'forwards', 'stealing', 'becoming', 'prepares',
        'prepared', 'powering', 'freeings', 'stations', 'possible', 'position', 'freshest', 'beddings', 'wrapping',
        'fronting', 'catching', 'fuckings', 'policing', 'funniest', 'pointers', 'pointing', 'catchers', 'pocketed',
        'gardened', 'starters', 'ceilings', 'pleasing', 'gathered', 'starting', 'centered', 'platings', 'plastics',
        'planning', 'pictured', 'pictures', 'traveler', 'pickings', 'personal', 'glancing', 'yourself', 'chancing',
        'perfects', 'changing', 'peopling', 'partying', 'partings', 'parented', 'grabbing', 'grabbers', 'changers',
        'checking', 'starring', 'bedrooms', 'checkers', 'pairings', 'standing', 'painting', 'outsides', 'greatest',
        'cheeking', 'greening', 'greenest', 'grouping', 'ordering', 'anything', 'openings', 'guarding', 'wheeling',
        'officers', 'guessing', 'spreader', 'offering', 'children', 'anywhere', 'numbered', 'choicest', 'noticers',
        'noticing', 'hallways', 'nothings', 'hangings', 'nobodies', 'admitted', 'neighbor', 'choosing', 'choosers',
        'happened', 'neckings', 'happiest', 'narrowed', 'narrower', 'spotting', 'churches', 'mouthing', 'traveled',
        'mountain', 'mothered', 'accepted', 'mornings', 'mirrored', 'headings', 'spirited', 'hearings', 'heatings',
        'circling', 'middling', 'messaged', 'messages', 'heaviest', 'wouldn’t', 'spinners', 'mentions', 'helpings',
        'cleanest', 'memories', 'meetings', 'meanings', 'appeared', 'mattered', 'marrieds', 'marrying', 'marriage',
        'yellowed', 'markings', 'cleaning', 'managing', 'cleaners', 'holdings', 'machined', 'machines', 'lunching',
        'luckiest', 'lowering', 'longings', 'clearest', 'hospital', 'lockings', 'littlest', 'clearing', 'listened',
        'housings', 'lightest', 'lighting', 'lighters', 'spinning', 'hundreds', 'hurrying', 'believes', 'spenders',
        'believed', 'climbing', 'husbands', 'lettered', 'lettings', 'learning', 'leadings', 'ignoring', 'laughing',
        'ignorers', 'imagines', 'yellower', 'imagined', 'climbers', 'imaginer', 'spending', 'closings', 'specials',
        'speakers', 'language', 'believer', 'clothing', 'clouding', 'speaking', 'interest', 'spacings', 'landings',
        'knowings', 'southest', 'jacketed', 'knocking', 'kitchens', 'kissings', 'killings', 'keepings', 'dresses',
        'biggest', 'sticker', 'careful', 'shirted', 'warmers', 'shipped', 'birding', 'drinker', 'carries', 'sheeted',
        'warming', 'carried', 'carrier', 'driving', 'sharper', 'tonight', 'drivers', 'casings', 'sharers', 'sharing',
        'stepped', 'dropped', 'dropper', 'whisper', 'shapers', 'shaping', 'shakers', 'shaking', 'tonguer', 'shadows',
        'stealer', 'several', 'tongued', 'staying', 'settles', 'settled', 'dusting', 'setting', 'tongues', 'catting',
        'backing', 'catches', 'earlier', 'warmest', 'earthed', 'service', 'serving', 'warring', 'wanters', 'catcher',
        'serious', 'eastest', 'sensing', 'senders', 'easiest', 'sending', 'sellers', 'selling', 'seeming', 'seeings',
        'tiniest', 'seconds', 'station', 'causing', 'seating', 'edgings', 'stating', 'timings', 'efforts', 'starter',
        'causers', 'screens', 'blacker', 'ceiling', 'screams', 'centers', 'wanting', 'walling', 'walkers', 'certain',
        'emptied', 'empties', 'emptier', 'thrower', 'endings', 'started', 'schools', 'scarers', 'scaring', 'sayings',
        'engines', 'savings', 'sanding', 'enjoyed', 'starers', 'saddest', 'enjoyer', 'staring', 'enoughs', 'rushing',
        'bagging', 'runners', 'entered', 'running', 'chances', 'entires', 'chancer', 'rubbing', 'rowings', 'rounder',
        'chanced', 'rounded', 'starred', 'rooming', 'changed', 'changes', 'blocked', 'angrier', 'exactly', 'changer',
        'blocker', 'excepts', 'checked', 'excited', 'walking', 'excites', 'roofing', 'through', 'expects', 'blooded',
        'checker', 'cheeked', 'throats', 'explain', 'wakings', 'springs', 'thought', 'waiting', 'blowing', 'rolling',
        'rocking', 'risings', 'ringing', 'baggers', 'animals', 'righter', 'righted', 'ridings', 'richest', 'facings',
        'reveals', 'blowers', 'choicer', 'choices', 'returns', 'voicing', 'worries', 'resting', 'chooses', 'failing',
        'spreads', 'replier', 'failers', 'falling', 'spotted', 'replies', 'replied', 'chooser', 'thinned', 'fallers',
        'thinner', 'balling', 'boarded', 'repeats', 'visitor', 'farther', 'further', 'circles', 'another', 'removed',
        'fastest', 'removes', 'fathers', 'thicker', 'circled', 'visited', 'reminds', 'fearing', 'spirits', 'classes',
        'answers', 'banking', 'boating', 'cleaned', 'feeding', 'spinner', 'thanked', 'village', 'worried', 'feeling',
        'cleaner', 'remains', 'cleared', 'refuses', 'refused', 'workers', 'reddest', 'telling', 'yellows', 'spender',
        'working', 'clearer', 'clearly', 'climbed', 'tearing', 'fighter', 'teaming', 'figured', 'figures', 'booking',
        'viewing', 'climber', 'usually', 'closest', 'receive', 'filling', 'teacher', 'reasons', 'closing', 'finally',
        'closers', 'anybody', 'finding', 'anymore', 'realize', 'special', 'finders', 'booting', 'realest', 'clothed',
        'readier', 'readies', 'readied', 'fingers', 'teaches', 'tallest', 'clothes', 'speaker', 'readers', 'talkers',
        'clouded', 'talking', 'reading', 'firings', 'spacing', 'takings', 'reacher', 'reached', 'coating', 'reaches',
        'raising', 'raining', 'fishing', 'quietly', 'fittest', 'fitting', 'systems', 'whether', 'bothers', 'wrapped',
        'fitters', 'quieted', 'quieter', 'quickly', 'coffees', 'quicker', 'fixings', 'coldest', 'sounded', 'sounder',
        'actings', 'anyways', 'college', 'flashed', 'flashes', 'bottles', 'flatter', 'flatted', 'colored', 'bottled',
        'wording', 'turning', 'sorting', 'flights', 'colorer', 'putting', 'pushers', 'pushing', 'flowers', 'pullers',
        'swinger', 'wonders', 'sorrier', 'pulling', 'proving', 'comings', 'bottoms', 'promise', 'truster', 'boxings',
        'company', 'follows', 'younger', 'trusted', 'sweeter', 'yelling', 'problem', 'without', 'beached', 'footing',
        'confuse', 'beaches', 'brained', 'bearing', 'pretend', 'trucked', 'forcing', 'presser', 'wishing', 'trouble',
        'forests', 'appears', 'beating', 'airings', 'forever', 'surface', 'control', 'forgets', 'accepts', 'pressed',
        'wronged', 'winters', 'forming', 'presses', 'prepare', 'beaters', 'breaker', 'wheeled', 'because', 'forward',
        'coolers', 'cooling', 'allowed', 'powered', 'pourers', 'freeing', 'pouring', 'tripped', 'coolest', 'breasts',
        'someone', 'fresher', 'suppose', 'somehow', 'friends', 'breaths', 'copping', 'fronted', 'becomes', 'porches',
        'poppers', 'popping', 'poorest', 'treeing', 'fucking', 'fullest', 'pooling', 'breathe', 'polices', 'funnier',
        'funnies', 'policed', 'bedding', 'corners', 'futures', 'pointer', 'pointed', 'gamings', 'counted', 'soldier',
        'pockets', 'wetting', 'pleased', 'gardens', 'wetters', 'wettest', 'pleases', 'counter', 'sunning', 'players',
        'westest', 'country', 'gathers', 'bridges', 'playing', 'plating', 'bridged', 'plastic', 'couples', 'softest',
        'getting', 'planned', 'getters', 'placing', 'gifting', 'pinking', 'pilings', 'piecing', 'picture', 'coursed',
        'courses', 'summers', 'picking', 'snowing', 'phoning', 'bedroom', 'glances', 'glanced', 'winging', 'snapped',
        'glassed', 'glasses', 'perhaps', 'covered', 'crazies', 'crazier', 'perfect', 'peopled', 'persons', 'peoples',
        'suiting', 'pausing', 'passing', 'goldest', 'partied', 'windows', 'parties', 'parting', 'creates', 'grabbed',
        'smokers', 'created', 'grabber', 'brought', 'weights', 'bringer', 'arrives', 'crosser', 'crosses', 'grasses',
        'parents', 'palming', 'graying', 'pairing', 'crossed', 'painted', 'arrived', 'greying', 'smoking', 'paining',
        'outside', 'brother', 'greater', 'smilers', 'outings', 'greened', 'greener', 'crowded', 'travels', 'smiling',
        'ordered', 'grounds', 'offings', 'smelled', 'openers', 'browner', 'grouped', 'opening', 'smaller', 'growing',
        'okaying', 'officer', 'guarded', 'slowest', 'slowing', 'cupping', 'slipped', 'guessed', 'guesses', 'cutting',
        'offices', 'gunning', 'offered', 'browned', 'allower', 'nursing', 'numbing', 'suggest', 'cutters', 'numbers',
        'sliders', 'halving', 'sliding', 'noticer', 'wedding', 'notices', 'noticed', 'nothing', 'writers', 'hallway',
        'handing', 'sleeper', 'normals', 'noising', 'hanging', 'nodding', 'dancing', 'wearing', 'writing', 'slammed',
        'hangers', 'darkest', 'skinned', 'happens', 'trained', 'needing', 'builder', 'beliefs', 'happier', 'necking',
        'nearest', 'hardest', 'nearing', 'burning', 'believe', 'winding', 'hatting', 'narrows', 'stupids', 'sitting',
        'mouthed', 'deadest', 'watered', 'sisters', 'mothers', 'singled', 'winning', 'morning', 'mooning', 'moments',
        'heading', 'missing', 'decides', 'decided', 'decider', 'mirrors', 'minutes', 'hearing', 'minings', 'already',
        'minding', 'middled', 'heating', 'burners', 'singles', 'middles', 'deepest', 'stuffed', 'heaters', 'singing',
        'simpler', 'heavier', 'heavies', 'belongs', 'message', 'despite', 'mention', 'simples', 'studies', 'studied',
        'silvers', 'helping', 'helpers', 'members', 'meeting', 'willing', 'meanest', 'attacks', 'herself', 'meaning',
        'dinners', 'student', 'hidings', 'matters', 'marries', 'married', 'busying', 'busiest', 'silence', 'against',
        'highest', 'wildest', 'hilling', 'marking', 'mapping', 'manages', 'managed', 'himself', 'history', 'tracked',
        'strikes', 'manning', 'hitting', 'makings', 'hitters', 'whiting', 'towards', 'watched', 'holding', 'toucher',
        'machine', 'holders', 'lunches', 'lunched', 'watches', 'luckier', 'stretch', 'streets', 'lowered', 'loudest',
        'lookers', 'looking', 'longing', 'calling', 'longest', 'locking', 'bending', 'washing', 'signing', 'hottest',
        'littler', 'benders', 'strange', 'sighted', 'listens', 'linings', 'likings', 'housing', 'beneath', 'sighing',
        'sicking', 'however', 'lighted', 'sickest', 'lighter', 'calming', 'lifters', 'hundred', 'calmest', 'hurried',
        'hurries', 'lifting', 'touched', 'doesnt', 'doesn’t', 'hurting', 'touches', 'showers', 'husband', 'doctors',
        'letters', 'cameras', 'letting', 'tossing', 'leaving', 'learned', 'dogging', 'leaning', 'leafing', 'leaders',
        'leading', 'whitest', 'layered', 'ignored', 'showing', 'ignores', 'stories', 'ignorer', 'shoving', 'laughed',
        'lasting', 'largest', 'imaging', 'doorway', 'besting', 'imagine', 'shouted', 'stormed', 'downing', 'storing',
        'topping', 'avoided', 'dragged', 'shorter', 'betters', 'stopper', 'landers', 'insides', 'instead', 'written',
        'drawing', 'shopped', 'stopped', 'between', 'landing', 'shooter', 'knowing', 'jackets', 'dreamed', 'carding',
        'toothed', 'knocked', 'knifing', 'kitchen', 'joining', 'teethed', 'stomach', 'joiners', 'kissing', 'kindest',
        'killers', 'killing', 'shoeing', 'kidding', 'jumping', 'kickers', 'kicking', 'jumpers', 'keepers', 'dressed',
        'keeping', 'enough', 'checks', 'kicked', 'jumper', 'kicker', 'kidded', 'jumped', 'killed', 'joking', 'killer',
        'kinder', 'joiner', 'kisses', 'kissed', 'joined', 'knives', 'knifes', 'knifed', 'jacket', 'knocks', 'itself',
        'ladies', 'landed', 'lander', 'inside', 'larger', 'images', 'lasted', 'imaged', 'laughs', 'ignore', 'aboves',
        'laying', 'accept', 'layers', 'across', 'yellow', 'leaded', 'leader', 'leaved', 'leaned', 'learns', 'leaves',
        'yelled', 'lesser', 'letter', 'living', 'lifted', 'lifter', 'humans', 'hugest', 'lights', 'wrongs', 'houses',
        'liking', 'likers', 'lining', 'housed', 'acting', 'listen', 'hotels', 'little', 'hotter', 'locals', 'locked',
        'horses', 'longer', 'longed', 'looked', 'hoping', 'looker', 'losing', 'adding', 'louder', 'loving', 'lovers',
        'lowing', 'lowest', 'writer', 'lowers', 'homing', 'holing', 'holder', 'making', 'hitter', 'makers', 'manned',
        'manage', 'writes', 'admits', 'mapped', 'marked', 'hilled', 'higher', 'afraid', 'hiding', 'hidden', 'matter',
        'ageing', 'helper', 'member', 'helped', 'memory', 'hellos', 'heater', 'metals', 'middle', 'heated', 'mights',
        'minded', 'hearts', 'mining', 'minute', 'headed', 'mirror', 'misses', 'missed', 'moment', 'moneys', 'monies',
        'months', 'mooned', 'mostly', 'having', 'mother', 'worlds', 'hating', 'mouths', 'moving', 'movers', 'movies',
        'musics', 'worker', 'myself', 'naming', 'namers', 'narrow', 'hatted', 'hardly', 'nearer', 'neared', 'nearly',
        'harder', 'necked', 'needed', 'happen', 'hanger', 'newest', 'nicest', 'nights', 'worked', 'nobody', 'nodded',
        'handed', 'noises', 'noised', 'worded', 'normal', 'norths', 'nosing', 'agrees', 'noting', 'notice', 'halves',
        'halved', 'number', 'guying', 'numbed', 'nurses', 'nursed', 'agreed', 'wooden', 'offing', 'gunned', 'offers',
        'office', 'guards', 'wonder', 'okayed', 'okayd', 'okay’d', 'oking', 'ok’ing', 'oldest', 'womens', 'opened',
        'opener', 'groups', 'womans', 'within', 'ground', 'orders', 'others', 'outing', 'wished', 'greens', 'greats',
        'owning', 'wishes', 'owners', 'paging', 'pained', 'paints', 'greyed', 'greyer', 'paired', 'palest', 'grayed',
        'palmed', 'papers', 'grayer', 'parent', 'parted', 'passed', 'golder', 'passes', 'pauses', 'paused', 'paying',
        'person', 'people', 'wipers', 'goings', 'glance', 'phones', 'phoned', 'photos', 'picked', 'giving', 'givens',
        'pieces', 'pieced', 'piling', 'gifted', 'pinked', 'pinker', 'places', 'placed', 'getter', 'gotten', 'plated',
        'plates', 'gently', 'played', 'gather', 'player', 'please', 'gating', 'garden', 'pocket', 'gamers', 'points',
        'pointy', 'gaming', 'future', 'wiping', 'fuller', 'police', 'pooled', 'poorer', 'fucked', 'popped', 'popper',
        'fronts', 'friend', 'freers', 'poured', 'pourer', 'freest', 'powers', 'formed', 'forget', 'forgot', 'forest',
        'forces', 'forced', 'footed', 'pretty', 'follow', 'fliers', 'flyers', 'proven', 'airing', 'proves', 'proved',
        'prover', 'pulled', 'flying', 'puller', 'flower', 'pushes', 'pushed', 'floors', 'pusher', 'flight', 'fixers',
        'fixing', 'quicks', 'winter', 'fitted', 'quiets', 'fitter', 'winged', 'radios', 'rained', 'raises', 'raised',
        'fishes', 'rather', 'fished', 'firsts', 'firing', 'reader', 'finish', 'finger', 'fining', 'finest', 'realer',
        'finder', 'really', 'finals', 'reason', 'filled', 'figure', 'fought', 'fights', 'fields', 'fewest', 'redder',
        'refuse', 'remain', 'feeing', 'remind', 'feared', 'father', 'faster', 'remove', 'repeat', 'family', 'faller',
        'fallen', 'failer', 'failed', 'rested', 'fading', 'return', 'reveal', 'riches', 'richer', 'riding', 'ridden',
        'window', 'riders', 'rights', 'facing', 'allows', 'ringed', 'rising', 'rivers', 'extras', 'rocked', 'rolled',
        'expect', 'roofed', 'excite', 'except', 'rooves', 'roomed', 'events', 'rounds', 'rowing', 'evened', 'rubbed',
        'almost', 'entire', 'runner', 'enters', 'keying', 'rushed', 'rushes', 'sadder', 'safest', 'sanded', 'enjoys',
        'saving', 'engine', 'savers', 'winded', 'saying', 'enders', 'scared', 'scares', 'scarer', 'scenes', 'ending',
        'school', 'scream', 'either', 'eights', 'screen', 'egging', 'effort', 'search', 'edging', 'seated', 'second',
        'eaters', 'seeing', 'seemed', 'eating', 'seller', 'sender', 'senses', 'sensed', 'easier', 'easily', 'earths',
        'serves', 'served', 'willed', 'dusted', 'settle', 'during', 'driers', 'sevens', 'sexing', 'shadow', 'shakes',
        'shaken', 'dryers', 'shaker', 'always', 'shaped', 'driest', 'shapes', 'shaper', 'drying', 'shares', 'shared',
        'sharer', 'sharps', 'driver', 'drives', 'driven', 'sheets', 'droves', 'drinks', 'shirts', 'drunks', 'shoots',
        'dreams', 'shorts', 'dozens', 'should', 'downed', 'shouts', 'shoved', 'shoves', 'showed', 'wilder', 'shower',
        'dogged', 'doctor', 'shrugs', 'didn’t', 'sicker', 'sicked', 'didnt', 'siding', 'sighed', 'doings', 'sights',
        'signed', 'dinner', 'silent', 'silver', 'dyings', 'widest', 'simple', 'simply', 'deeper', 'single', 'decide',
        'deaths', 'sister', 'deader', 'sizing', 'darker', 'wholes', 'sleeps', 'dances', 'danced', 'slides', 'slider',
        'cutter', 'slower', 'slowed', 'slowly', 'smalls', 'cupped', 'smells', 'smelly', 'crying', 'smiles', 'smiled',
        'smiler', 'crowds', 'smokes', 'smoked', 'smoker', 'create', 'covers', 'snowed', 'whited', 'softer', 'course',
        'softly', 'couple', 'counts', 'corner', 'whiter', 'copped', 'cooled', 'cooler', 'coming', 'whites', 'sorted',
        'colors', 'colder', 'sounds', 'coffee', 'coated', 'spaces', 'clouds', 'spaced', 'spoken', 'speaks', 'clothe',
        'closed', 'closes', 'closer', 'spends', 'climbs', 'clears', 'cleans', 'spirit', 'cities', 'circle', 'church',
        'choose', 'spread', 'chosen', 'choice', 'chests', 'sprung', 'spring', 'sprang', 'stages', 'stairs', 'cheeks',
        'stands', 'keeper', 'change', 'chance', 'stared', 'stares', 'starer', 'chairs', 'starts', 'center', 'causer',
        'caused', 'states', 'stated', 'causes', 'caught', 'catted', 'stayed', 'steals', 'stolen', 'casing', 'sticks',
        'caring', 'carded', 'stones', 'animal', 'cannot', 'stored', 'stores', 'storms', 'answer', 'camera', 'calmer',
        'calmed', 'called', 'street', 'buyers', 'bought', 'strike', 'struck', 'buying', 'anyone', 'strong', 'busier',
        'busied', 'busing', 'burner', 'stuffs', 'burned', 'stupid', 'builds', 'browns', 'suites', 'suited', 'brings',
        'summer', 'bright', 'sunned', 'bridge', 'breath', 'breast', 'breaks', 'broken', 'surest', 'branch', 'brains',
        'anyway', 'boxing', 'wheels', 'sweets', 'swings', 'bottom', 'bottle', 'system', 'bother', 'tables', 'taking',
        'takers', 'talked', 'talker', 'boring', 'taller', 'booted', 'taught', 'booked', 'teamed', 'teared', 'boning',
        'appear', 'bodies', 'thanks', 'boated', 'thicks', 'boards', 'bluest', 'things', 'thinks', 'blower', 'thirds',
        'thirty', 'though', 'threes', 'throat', 'bloods', 'thrown', 'throws', 'blocks', 'timing', 'blacks', 'timers',
        'tinier', 'biters', 'tiring', 'todays', 'biting', 'toning', 'tongue', 'arming', 'birded', 'bigger', 'wetter',
        'toothy', 'beyond', 'better', 'topped', 'tossed', 'bested', 'tosses', 'beside', 'bender', 'toward', 'bended',
        'tracks', 'belong', 'trains', 'belief', 'travel', 'behind', 'begins', 'before', 'bedded', 'became', 'become',
        'beater', 'beaten', 'trucks', 'truest', 'aren’t', 'arent', 'trusts', 'truths', 'trying', 'turned', 'twenty',
        'around', 'uncles', 'weight', 'wasn’t', 'wasnt', 'arrive', 'unless', 'upping', 'wedded', 'viewed', 'barely',
        'visits', 'banked', 'balled', 'voices', 'voiced', 'waited', 'bagger', 'waking', 'walked', 'bagged', 'walker',
        'walled', 'asking', 'wanted', 'wanter', 'warred', 'waring', 'backed', 'warmed', 'warmer', 'babies', 'washed',
        'washes', 'avoids', 'attack', 'waters', 'asleep', 'watery', 'waving', 'wavers', 'seems', 'party', 'minds',
        'eaten', 'sells', 'sends', 'known', 'sense', 'hours', 'pasts', 'paths', 'easts', 'pause', 'mined', 'layer',
        'payed', 'serve', 'earth', 'early', 'wills', 'aired', 'heard', 'hears', 'dusts', 'kills', 'goers', 'hotel',
        'seven', 'dried', 'ideas', 'sexed', 'sexes', 'going', 'drier', 'dries', 'dryer', 'glass', 'heads', 'shake',
        'leads', 'shook', 'aging', 'gives', 'phone', 'local', 'photo', 'shape', 'picks', 'above', 'locks', 'money',
        'drops', 'share', 'given', 'wrong', 'girls', 'month', 'sharp', 'piece', 'wilds', 'sheet', 'drove', 'drive',
        'moons', 'lands', 'piles', 'ships', 'drink', 'piled', 'drank', 'drunk', 'shirt', 'pinks', 'shits', 'dress',
        'shoes', 'mores', 'shoot', 'longs', 'shots', 'dream', 'drawn', 'draws', 'drags', 'shops', 'haves', 'horse',
        'short', 'gifts', 'dozen', 'place', 'downs', 'shout', 'hopes', 'shove', 'hoped', 'plans', 'wiper', 'doors',
        'shown', 'shows', 'wiped', 'plate', 'world', 'mouth', 'doers', 'joins', 'shrug', 'shuts', 'leafs', 'moved',
        'plays', 'moves', 'sicks', 'don’t', 'pleas', 'sided', 'sides', 'sighs', 'dont', 'gated', 'sight', 'looks',
        'gates', 'wives', 'mover', 'signs', 'doing', 'dirts', 'knees', 'movie', 'learn', 'gamer', 'games', 'gamed',
        'dying', 'music', 'since', 'desks', 'sings', 'singe', 'deeps', 'point', 'acted', 'musts', 'yells', 'funny',
        'death', 'wider', 'loses', 'sixes', 'whose', 'names', 'sizes', 'sized', 'skins', 'keyed', 'skies', 'pools',
        'slams', 'darks', 'named', 'slept', 'namer', 'sleep', 'leave', 'dance', 'slide', 'hated', 'young', 'whole',
        'fucks', 'who’s', 'slips', 'whos', 'slows', 'front', 'porch', 'loved', 'hates', 'small', 'fresh', 'cries',
        'cried', 'smell', 'white', 'nears', 'loves', 'smile', 'freer', 'pours', 'lover', 'freed', 'power', 'smoke',
        'frees', 'yeses', 'crowd', 'cross', 'jokes', 'fours', 'snaps', 'crazy', 'forms', 'cover', 'homed', 'snows',
        'among', 'necks', 'happy', 'least', 'press', 'force', 'homes', 'count', 'needs', 'wipes', 'years', 'cools',
        'foots', 'joked', 'foods', 'never', 'songs', 'comes', 'sorry', 'flier', 'color', 'sorts', 'souls', 'lower',
        'newer', 'flyer', 'colds', 'sound', 'flown', 'south', 'works', 'coats', 'space', 'nicer', 'prove', 'lucky',
        'spoke', 'night', 'speak', 'cloud', 'hurts', 'yards', 'pulls', 'holed', 'flies', 'close', 'climb', 'spent',
        'spend', 'words', 'holes', 'hangs', 'clear', 'lunch', 'spins', 'clean', 'class', 'liars', 'floor', 'holds',
        'spots', 'alive', 'noise', 'flats', 'chose', 'flash', 'nones', 'child', 'fixer', 'fixed', 'fixes', 'chest',
        'cheek', 'mains', 'stage', 'hands', 'makes', 'stair', 'quick', 'stood', 'check', 'fiver', 'stand', 'stars',
        'fives', 'north', 'wrote', 'stare', 'lying', 'quiet', 'noses', 'quite', 'start', 'chair', 'nosed', 'radio',
        'lived', 'rains', 'notes', 'state', 'large', 'cause', 'raise', 'catch', 'noted', 'maker', 'stays', 'halls',
        'angry', 'stole', 'steal', 'reach', 'first', 'cased', 'cases', 'steps', 'lives', 'fires', 'stuck', 'carry',
        'stick', 'cares', 'still', 'cared', 'fired', 'cards', 'added', 'stone', 'reads', 'halve', 'stops', 'write',
        'can’t', 'ready', 'hairy', 'store', 'hairs', 'cant', 'storm', 'numbs', 'story', 'could', 'finer', 'knife',
        'fines', 'calms', 'fined', 'calls', 'hurry', 'while', 'buyer', 'finds', 'nurse', 'found', 'which', 'lifts',
        'admit', 'final', 'fills', 'lasts', 'keeps', 'where', 'buses', 'bused', 'study', 'offed', 'stuff', 'fight',
        'woods', 'burnt', 'burns', 'field', 'human', 'build', 'built', 'wings', 'offer', 'brown', 'allow', 'guyed',
        'suite', 'suits', 'bring', 'marks', 'fewer', 'feels', 'hills', 'wines', 'later', 'feeds', 'agree', 'guess',
        'surer', 'fears', 'broke', 'break', 'guard', 'brain', 'highs', 'often', 'marry', 'ahead', 'knock', 'boxes',
        'sweet', 'boxed', 'okays', 'swing', 'swung', 'falls', 'reply', 'hides', 'fails', 'huger', 'table', 'takes',
        'taken', 'laugh', 'taker', 'rests', 'house', 'talks', 'bored', 'women', 'faded', 'fades', 'wheel', 'facts',
        'wraps', 'boots', 'teach', 'faces', 'teams', 'older', 'books', 'tears', 'bones', 'maybe', 'woman', 'faced',
        'areas', 'boned', 'opens', 'tells', 'rides', 'grows', 'thank', 'their', 'boats', 'thens', 'there', 'these',
        'thick', 'rider', 'after', 'board', 'right', 'bluer', 'thins', 'blues', 'blued', 'grown', 'thing', 'again',
        'rings', 'think', 'blows', 'blown', 'third', 'would', 'means', 'those', 'risen', 'three', 'rises', 'blood',
        'eying', 'heres', 'throw', 'block', 'threw', 'roses', 'group', 'river', 'black', 'tying', 'times', 'timed',
        'roads', 'rocks', 'order', 'timer', 'meant', 'green', 'tired', 'tires', 'extra', 'meets', 'today', 'rolls',
        'biter', 'bitey', 'other', 'toned', 'tones', 'light', 'bites', 'worry', 'birds', 'roofs', 'armed', 'outer',
        'rooms', 'outed', 'every', 'tooth', 'teeth', 'round', 'image', 'bests', 'event', 'liked', 'evens', 'rowed',
        'likes', 'touch', 'bends', 'windy', 'bents', 'towns', 'winds', 'great', 'below', 'track', 'overs', 'owned',
        'liker', 'train', 'enter', 'wound', 'begun', 'helps', 'began', 'begin', 'owner', 'beers', 'kinds', 'wests',
        'paged', 'trees', 'treed', 'tripe', 'trips', 'pages', 'alone', 'hello', 'beats', 'enjoy', 'bears', 'truck',
        'beach', 'safer', 'trues', 'truer', 'trued', 'safes', 'hells', 'sames', 'trust', 'truth', 'pains', 'wells',
        'sands', 'tried', 'tries', 'greys', 'turns', 'isn’t', 'isnt', 'heavy', 'twice', 'saves', 'uncle', 'saved',
        'under', 'kicks', 'saver', 'paint', 'lines', 'grays', 'until', 'weeks', 'upped', 'pairs', 'using', 'asked',
        'usual', 'scare', 'being', 'ender', 'metal', 'views', 'paled', 'banks', 'visit', 'pales', 'paler', 'voice',
        'scene', 'heats', 'waits', 'balls', 'ended', 'empty', 'woken', 'palms', 'wakes', 'waked', 'walks', 'lined',
        'knows', 'pants', 'worse', 'paper', 'walls', 'worst', 'wants', 'eight', 'heart', 'along', 'backs', 'egged',
        'jumps', 'warms', 'grass', 'might', 'edges', 'grabs', 'seats', 'avoid', 'parts', 'edged', 'aunts', 'watch',
        'about', 'eater', 'won’t', 'water', 'wont', 'waved', 'waves', 'goods', 'waver', 'golds', 'wears', 'ears',
        'grab', 'fits', 'each', 'sets', 'knee', 'lots', 'part', 'dust', 'noes', 'fish', 'stay', 'good', 'rain', 'cats',
        'work', 'wild', 'laid', 'hang', 'gold', 'pass', 'step', 'loud', 'case', 'help', 'your', 'past', 'nods', 'home',
        'care', 'path', 'hell', 'read', 'love', 'fire', 'gods', 'lift', 'card', 'stop', 'pays', 'keys', 'cars', 'paid',
        'idea', 'fine', 'none', 'real', 'into', 'drop', 'heat', 'wish', 'cans', 'kids', 'find', 'goer', 'goes', 'went',
        'calm', 'just', 'lead', 'gone', 'call', 'fill', 'nose', 'ship', 'huge', 'acts', 'lows', 'buys', 'some', 'note',
        'kind', 'shit', 'shat', 'mind', 'ices', 'busy', 'pick', 'hand', 'shod', 'shoe', 'gave', 'reds', 'shot', 'hall',
        'fews', 'ours', 'feel', 'burn', 'drew', 'such', 'draw', 'shop', 'give', 'felt', 'wing', 'suit', 'drag', 'hear',
        'feed', 'mine', 'girl', 'feds', 'iced', 'down', 'when', 'fees', 'half', 'suns', 'able', 'word', 'fear', 'nows',
        'door', 'fast', 'sure', 'leaf', 'pile', 'jobs', 'show', 'wine', 'boys', 'dogs', 'yell', 'hair', 'guys', 'kept',
        'doer', 'fall', 'fell', 'head', 'shut', 'gift', 'hole', 'rest', 'numb', 'kick', 'lean', 'take', 'both', 'sick',
        'fail', 'fade', 'took', 'miss', 'side', 'sigh', 'held', 'talk', 'last', 'plan', 'bore', 'hold', 'done', 'tall',
        'teas', 'fact', 'boot', 'like', 'wife', 'rich', 'sign', 'book', 'wood', 'team', 'does', 'main', 'offs', 'tear',
        'tore', 'torn', 'rode', 'dirt', 'gets', 'bone', 'joke', 'ride', 'make', 'told', 'play', 'died', 'tell', 'dies',
        'tens', 'area', 'body', 'than', 'boat', 'line', 'guns', 'desk', 'that', 'what', 'kiss', 'them', 'they', 'gate',
        'sang', 'then', 'plea', 'kill', 'face', 'sing', 'sung', 'eyes', 'thin', 'blue', 'deep', 'made', 'rung', 'ring',
        'sirs', 'wide', 'he’s', 'rang', 'moon', 'blow', 'eyed', 'sits', 'more', 'whys', 'dead', 'blew', 'days', 'this',
        'left', 'grew', 'hes', 'size', 'rise', 'rose', 'whom', 'have', 'skin', 'most', 'late', 'grow', 'slam', 'road',
        'game', 'tied', 'ties', 'arms', 'time', 'dark', 'rock', 'okay', 'ages', 'mens', 'roll', 'mans', 'tiny', 'slid',
        'dads', 'airs', 'okd', 'tire', 'wets', 'ok’d', 'i’ll', 'roof', 'slip', 'full', 'cuts', 'pool', 'slow', 'tone',
        'bite', 'lips', 'cups', 'bits', 'room', 'olds', 'poor', 'bird', 'adds', 'ever', 'knew', 'hate', 'fuck', 'pops',
        'even', 'tops', 'wipe', 'hits', 'once', 'west', 'hour', 'rows', 'rubs', 'toss', 'best', 'ones', 'only', 'from',
        'runs', 'bend', 'bent', 'onto', 'open', 'move', 'town', 'free', 'pour', 'legs', 'rush', 'jump', 'snap', 'many',
        'hill', 'less', 'maps', 'snow', 'keep', 'safe', 'much', 'soft', 'join', 'beer', 'ill', 'beds', 'four', 'tree',
        'same', 'sand', 'form', 'cops', 'must', 'year', 'cool', 'trip', 'lets', 'beat', 'mark', 'born', 'bear', 'with',
        'come', 'save', 'know', 'true', 'sons', 'lock', 'song', 'soon', 'laws', 'came', 'outs', 'name', 'well', 'been',
        'says', 'said', 'sort', 'feet', 'soul', 'high', 'yeah', 'were', 'hide', 'foot', 'turn', 'cold', 'wind', 'yard',
        'twos', 'coat', 'food', 'over', 'hats', 'owns', 'ends', 'lady', 'aged', 'arts', 'else', 'long', 'flew', 'hurt',
        'page', 'week', 'upon', 'lays', 'used', 'uses', 'hard', 'eggs', 'wins', 'very', 'mays', 'seas', 'pain', 'near',
        'view', 'bars', 'weds', 'pull', 'edge', 'wrap', 'lies', 'bank', 'spin', 'ball', 'grey', 'seat', 'spun', 'lied',
        'neck', 'push', 'wait', 'hope', 'bags', 'city', 'look', 'wake', 'spot', 'saws', 'woke', 'wear', 'pink', 'liar',
        'eats', 'walk', 'need', 'sees', 'seen', 'puts', 'seem', 'wall', 'want', 'pair', 'gray', 'sell', 'will', 'flat',
        'back', 'pale', 'sold', 'asks', 'wars', 'land', 'send', 'mean', 'warm', 'baby', 'sent', 'also', 'wash', 'away',
        'here', 'easy', 'hung', 'sens', 'star', 'hers', 'aunt', 'palm', 'worn', 'life', 'meet', 'wore', 'east', 'live',
        'news', 'five', 'wave', 'next', 'lost', 'lose', 'nice', 'ways', 'far', 'few', 'war', 'bad', 'bag', 'bar', 'wed',
        'use', 'ups', 'art', 'was', 'two', 'try', 'are', 'bed', 'top', 'arm', 'wet', 'big', 'too', 'bit', 'tie', 'the',
        'ten', 'tvs', 'tea', 'box', 'boy', 'sun', 'bus', 'but', 'buy', 'any', 'can', 'car', 'cat', 'and', 'son', 'cop',
        'sos', 'cry', 'cup', 'cut', 'who', 'dad', 'sky', 'day', 'six', 'why', 'sit', 'sat', 'sir', 'die', 'did', 'dog',
        'she', 'dry', 'sex', 'set', 'ear', 'ate', 'eat', 'see', 'saw', 'win', 'won', 'sea', 'egg', 'end', 'say', 'sad',
        'ran', 'run', 'rub', 'row', 'eye', 'rid', 'ask', 'fed', 'fee', 'red', 'way', 'fit', 'fix', 'all', 'put', 'fly',
        'for', 'pop', 'fun', 'get', 'got', 'god', 'pay', 'own', 'out', 'our', 'air', 'ors', 'one', 'old', 'ohs', 'gun',
        'key', 'off', 'guy', 'now', 'not', 'nor', 'nod', 'nos', 'ago', 'new', 'hat', 'age', 'had', 'has', 'her', 'met',
        'hey', 'may', 'hid', 'map', 'him', 'add', 'his', 'man', 'men', 'hit', 'mad', 'low', 'lot', 'hot', 'lip', 'how',
        'lit', 'lie', 'kid', 'im', 'let', 'i’m', 'leg', 'id', 'i’d', 'ice', 'led', 'act', 'lay', 'law', 'ins', 'yes',
        'yet', 'you', 'its', 'job', 'no', 'at', 'by', 'my', 'on', 'ha', 'do', 'ok', 'he', 'oh', 'is', 'tv', 'me', 'us',
        'as', 'hi', 'go', 'if', 'of', 'am', 'up', 'to', 'we', 'so', 'in', 'or', 'it', 'be', 'an', 'i', 'a'
    ]

    @classmethod
    def en_word(cls):
        """
        Generate a random word
        :example 'lorem'
        """
        return cls.random_element(cls.words)

    @classmethod
    def en_line(cls):
        """
        Generate an array of random words
        :example array('Lorem', 'ipsum', 'dolor')
        :param nb how many words to return
        """
        return cls.random_element(cls.sentences) + '.'

    @classmethod
    def en_paragraph(cls):
        nb = cls.randomize_nb_elements()
        lines = [cls.en_line() for i in range(0, nb)]
        return ' '.join(lines)
